# Generated by Django 4.2.30 on 2026-08-11 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(5, '★★★★★ - Excellent'), (4, '★★★★☆ - Very Good'), (3, '★★★☆☆ - Good'), (2, '★★☆☆☆ - Fair'), (1, '★☆☆☆☆ - Poor')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
