from rest_framework import serializers

from .models import Store, Product, Review


class StoreSerializer(serializers.ModelSerializer):
    """
    Converts Store model instances into JSON-compatible data.

    The serializer exposes the basic store information needed
    by API clients while keeping the model itself unchanged.
    """

    class Meta:
        model = Store

        fields = [
            "id",
            "owner",
            "name",
            "description",
            "created_at",
        ]

        # The owner is displayed through the API but should not
        # be changed directly by an API client.
        read_only_fields = [
            "id",
            "owner",
            "created_at",
        ]


class ProductSerializer(serializers.ModelSerializer):
    """
    Converts Product model instances into JSON-compatible data.

    Product data can therefore be returned to clients through
    our REST API without affecting the existing HTML views.
    """

    class Meta:
        model = Product

        fields = [
            "id",
            "store",
            "name",
            "description",
            "price",
            "stock",
            "image",
            "available",
            "created_at",
            "updated_at",
        ]

        # These values are generated by Django and should not
        # be manually supplied by an API client.
        read_only_fields = [
            "id",
            "created_at",
            "updated_at",
        ]


class ReviewSerializer(serializers.ModelSerializer):
    """
    Converts Review model instances into JSON-compatible data.

    The reviewer and verification status are controlled by the
    application rather than being supplied freely by clients.
    """


    review_username = serializers.CharField(
        source="reviewer.username",
        read_only=True,
    )

    class Meta:
        model = Review

        fields = [
            "id",
            "product",
            "reviewer",
            "review_username",
            "rating",
            "comment",
            "verified",
            "created_at",
        ]

        # Prevent clients from pretending to be another reviewer
        # or manually marking their own review as verified.
        read_only_fields = [
            "id",
            "reviewer",
            "verified",
            "created_at",
        ]